name: CD Deploy to Ubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Deploy locally on runner
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
          cd /home/deployer/deploy/is-stack
          docker compose pull
          docker compose up -d
          docker image prune -fx

